# Imports

In [1]:
import sys, os
if not sys.path[0] == os.path.abspath('../..'):
    sys.path.insert(0, os.path.abspath('../..'))

from drafts.hyperparameters.utils import show_results_cv, show_results_ho

# IMLIB vs DI-IMLIB vs Decision Tree (Cross Validation)

In [2]:
show_results_cv(
    ['imlib', 'diimlib', 'decision_tree'], 
    ['lung_cancer', 'iris', 'parkinsons','ionosphere','wdbc', 'transfusion', 'pima', 'titanic', 'depressed', 'mushroom']
)

,Datasets,Models,Number of rules,|R|,Largest rule size,Accuracy,Training time
0,lung_cancer,imlib,3.00 ± 0.00,3.20 ± 0.41,1.20 ± 0.41,0.9102 ± 0.1268,0.021104 ± 0.020454
1,lung_cancer,diimlib,1.27 ± 0.46,2.60 ± 1.18,2.13 ± 0.74,0.9093 ± 0.1102,0.019787 ± 0.016919
2,lung_cancer,decision_tree,2.00 ± 0.00,2.00 ± 0.00,1.00 ± 0.00,0.9278 ± 0.0743,0.000166 ± 0.000361
3,iris,imlib,1.00 ± 0.00,2.87 ± 0.74,2.87 ± 0.74,0.9302 ± 0.0505,0.021113 ± 0.024766
4,iris,diimlib,2.27 ± 0.80,6.60 ± 2.56,3.27 ± 0.46,0.9302 ± 0.0354,0.035783 ± 0.035827
5,iris,decision_tree,4.00 ± 0.00,9.00 ± 0.00,3.00 ± 0.00,0.9556 ± 0.0380,0.000319 ± 0.000557
6,parkinsons,imlib,2.00 ± 0.00,2.00 ± 0.00,1.00 ± 0.00,0.8235 ± 0.0826,0.364245 ± 0.155344
7,parkinsons,diimlib,2.27 ± 1.10,5.67 ± 3.68,2.93 ± 0.80,0.8381 ± 0.0538,0.434358 ± 0.327506
8,parkinsons,decision_tree,4.00 ± 0.00,8.00 ± 0.00,2.00 ± 0.00,0.8334 ± 0.0359,0.000439 ± 0.000566
9,ionosphere,imlib,1.00 ± 0.00,2.00 ± 0.00,2.00 ± 0.00,0.8571 ± 0.0456,0.115900 ± 0.051576
10,ionosphere,diimlib,1.47 ± 0.64,4.27 ± 1.94,3.20 ± 0.77,0.8626 ± 0.0514,0.258417 ± 0.094186
11,ionosphere,decision_tree,3.00 ± 0.00,5.00 ± 0.00,2.00 ± 0.00,0.9034 ± 0.0366,0.001757 ± 0.000520
12,wdbc,imlib,2.00 ± 0.00,3.33 ± 0.49,2.00 ± 0.00,0.9104 ± 0.0360,0.149801 ± 0.053825
13,wdbc,diimlib,2.00 ± 0.76,4.93 ± 2.40,2.73 ± 0.70,0.9206 ± 0.0431,0.313323 ± 0.111928
14,wdbc,decision_tree,4.00 ± 0.00,8.73 ± 0.46,2.73 ± 0.46,0.9488 ± 0.0228,0.001370 ± 0.000421
15,transfusion,imlib,1.00 ± 0.00,1.27 ± 0.46,1.27 ± 0.46,0.7527 ± 0.0154,0.098943 ± 0.021438
16,transfusion,diimlib,1.00 ± 0.00,3.07 ± 0.70,3.07 ± 0.70,0.7323 ± 0.0483,0.063496 ± 0.015585
17,transfusion,decision_tree,4.00 ± 0.00,9.00 ± 0.00,3.00 ± 0.00,0.7795 ± 0.0285,0.000585 ± 0.000515
18,pima,imlib,1.00 ± 0.00,1.07 ± 0.26,1.07 ± 0.26,0.7324 ± 0.0415,0.293149 ± 0.133898
19,pima,diimlib,1.00 ± 0.00,1.07 ± 0.26,1.07 ± 0.26,0.7324 ± 0.0415,0.284230 ± 0.158868
20,pima,decision_tree,4.00 ± 0.00,8.80 ± 0.41,2.80 ± 0.41,0.7480 ± 0.0302,0.000431 ± 0.000558
21,titanic,imlib,1.00 ± 0.00,1.00 ± 0.00,1.00 ± 0.00,0.7784 ± 0.0220,0.030776 ± 0.012464
22,titanic,diimlib,1.00 ± 0.00,1.00 ± 0.00,1.00 ± 0.00,0.7784 ± 0.0220,0.028164 ± 0.004740
23,titanic,decision_tree,4.00 ± 0.00,8.33 ± 0.49,2.33 ± 0.49,0.7766 ± 0.0254,0.000609 ± 0.000540
24,depressed,imlib,1.00 ± 0.00,2.07 ± 0.26,2.07 ± 0.26,0.8110 ± 0.0149,0.697906 ± 0.203390
25,depressed,diimlib,1.00 ± 0.00,1.80 ± 0.41,1.80 ± 0.41,0.7953 ± 0.0351,0.478260 ± 0.151138
26,depressed,decision_tree,2.00 ± 0.00,2.00 ± 0.00,1.00 ± 0.00,0.8330 ± 0.0025,0.000739 ± 0.000554
27,mushroom,imlib,3.00 ± 0.00,5.13 ± 0.92,2.00 ± 0.00,0.9851 ± 0.0156,0.289474 ± 0.063229
28,mushroom,diimlib,1.00 ± 0.00,4.00 ± 0.00,4.00 ± 0.00,0.9777 ± 0.0098,0.352297 ± 0.079614
29,mushroom,decision_tree,4.00 ± 0.00,9.00 ± 0.00,3.00 ± 0.00,0.9666 ± 0.0037,0.006579 ± 0.001225

# IMLIB vs DI-IMLIB vs Decision Tree (Holdout)

In [3]:
show_results_ho(
    ['imlib', 'diimlib', 'decision_tree'], 
    ['lung_cancer', 'iris', 'parkinsons','ionosphere','wdbc', 'transfusion', 'pima', 'titanic', 'depressed', 'mushroom']
)

,Datasets,Models,Number of rules,|R|,Largest rule size,Accuracy,Training time
0,lung_cancer,imlib,3.00,3.00,1.00,0.8889,0.005336
1,lung_cancer,diimlib,2.00,5.00,3.00,0.8333,0.009349
2,lung_cancer,decision_tree,2.00,2.00,1.00,0.8889,0.000000
3,iris,imlib,1.00,4.00,4.00,0.9111,0.016627
4,iris,diimlib,1.00,3.00,3.00,0.8889,0.014133
5,iris,decision_tree,4.00,9.00,3.00,1.0000,0.000000
6,parkinsons,imlib,2.00,2.00,1.00,0.7627,0.115177
7,parkinsons,diimlib,1.00,2.00,2.00,0.7966,0.221587
8,parkinsons,decision_tree,4.00,8.00,2.00,0.8136,0.000996
9,ionosphere,imlib,1.00,2.00,2.00,0.8302,0.133676
10,ionosphere,diimlib,2.00,5.00,3.00,0.8585,0.125248
11,ionosphere,decision_tree,3.00,5.00,2.00,0.9057,0.003193
12,wdbc,imlib,2.00,3.00,2.00,0.8889,0.049342
13,wdbc,diimlib,3.00,7.00,3.00,0.8363,0.116624
14,wdbc,decision_tree,4.00,9.00,3.00,0.9240,0.001072
15,transfusion,imlib,1.00,3.00,3.00,0.7644,0.028056
16,transfusion,diimlib,1.00,3.00,3.00,0.7644,0.036220
17,transfusion,decision_tree,2.00,2.00,1.00,0.7600,0.000000
18,pima,imlib,1.00,1.00,1.00,0.7186,0.078432
19,pima,diimlib,1.00,1.00,1.00,0.7186,0.082225
20,pima,decision_tree,4.00,9.00,3.00,0.6623,0.000998
21,titanic,imlib,1.00,1.00,1.00,0.7837,0.018487
22,titanic,diimlib,1.00,1.00,1.00,0.7837,0.017529
23,titanic,decision_tree,4.00,8.00,2.00,0.7888,0.000998
24,depressed,imlib,1.00,1.00,1.00,0.8252,0.125841
25,depressed,diimlib,1.00,2.00,2.00,0.8275,0.168313
26,depressed,decision_tree,2.00,2.00,1.00,0.8345,0.001127
27,mushroom,imlib,3.00,6.00,2.00,0.9672,0.147799
28,mushroom,diimlib,1.00,4.00,4.00,0.9692,0.201467
29,mushroom,decision_tree,4.00,9.00,3.00,0.9746,0.006939